### ISSUE TITLE
location of `cubic-elements-dict.json`?

### ISSUE THREAD

**Issue by newalexander** [MilesZhao/CubicGAN#2]
Hello!

This is a nice work, and thanks for making it public. I'm trying to work through `generate_crystal.py`; this script loads in a `cubic-elements-dict.json` file in a few places (https://github.com/MilesZhao/CubicGAN/blob/main/generate_crystal.py#L36). I don't think this file is on the repo anywhere, could you please add it?

Thanks!

**Comment by MilesZhao** [comment]
You need to read our code carefully. Then you will know why this file is not in repo!
